# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Blogfolio - James Dowell
email: jamesdowell1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have decided to start blog about front-end tech and what I have learned in my career so far. All in the faint hope it might be useful to someone else.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamesdowell.me" # the base hostname & protocol for your site
twitter_username: jmwdowell
github_username:  james-dowell
permalink: /:categories/:title

exclude: ['pattern-library']
# Build settings
markdown: kramdown
show_drafts: false
